###
# File: .drone.yml
# Author: Ming Cheng<mingcheng@outlook.com>
###

kind: pipeline
type: docker
name: build_on_docker

steps:
  - name: build_and_test
    image: golang:1.13.9
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make clean
      - make build
      - ./smart-exporter --version
      - make test
