###
# File: .drone.yml
# Author: Ming Cheng<mingcheng@outlook.com>
###

kind: pipeline
type: docker
name: build_on_docker

steps:
  - name: build
    image: golang:1.13.8
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make clean
      - make build
      - ./smart-exporter --script
      - ./smart-exporter --version
